import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'kc_language';

const translations = {
  en: {
    home: 'Home',
    history: 'History',
    transactions: 'Transactions',
    profile: 'Profile',
    terms: 'Terms',
    privacy: 'Privacy',
    dashboard: 'Dashboard',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    register: 'Register',
    createAccount: 'Create Account',
    openDashboard: 'Open Dashboard',
    recordSale: 'Record Sale',
    welcomeBack: 'Welcome back, {name}!',
    businessOverviewToday: 'Here is your business overview today.',
    todaysRevenue: "TODAY'S REVENUE",
    filteredRevenue: 'FILTERED REVENUE',
    usdTotal: 'USD total:',
    khrSeparate: 'KHR total stays separate',
    totalOrders: 'Total Orders',
    recentTransactions: 'Recent transactions',
    viewAll: 'View all',
    noTransactions: 'No transactions yet.',
    loadingTransactions: 'Loading transactions...',
    unableDashboard: 'Unable to load dashboard data.',
    unableHistory: 'Unable to load history data.',
    productSummary: 'Product Summary',
    totalItems: 'Total Items',
    productTypes: 'types of products',
    totalQuantity: 'Total Quantity',
    items: 'items',
    product: 'Product',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    total: 'Total',
    noProducts: 'No products in this period.',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    selectDate: 'Select Date',
    reviewConfirmSale: 'Review & Confirm Sale',
    editTransaction: 'Edit Transaction',
    transactionDetails: 'Transaction Details',
    aiExtractionComplete: 'AI Extraction Complete!',
    reviewBeforeSaving: "We've captured the details. Please review quantities and prices before saving.",
    rerecord: 'Re-record',
    foundItems: 'We found the following items:',
    totalAmount: 'Total amount:',
    editItems: 'Edit Items',
    confirmSaveSale: 'Confirm & Save Sale',
    saving: 'Saving...',
    noReviewItems: 'No reviewed sale items are available to save.',
    addOneItem: 'Add at least one sale item before saving.',
    unableRequest: 'Unable to complete request. Please try again.',
    date: 'Date:',
    totalKHR: 'Total KHR:',
    totalUSD: 'Total USD:',
    edit: 'Edit',
    delete: 'Delete',
    transactionSaved: 'Transaction Saved',
    saleAdded: "Your sale has been added to today's revenue.",
    recordAnotherSale: 'Record Another Sale',
    backHome: 'Back to Home',
    ownerName: 'Owner Name',
    firstName: 'First Name',
    lastName: 'Last Name',
    businessName: 'Business Name',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    address: 'Address',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated successfully.',
    unableProfile: 'Unable to update profile.',
    account: 'Account',
    myAccount: 'My Account',
    makeChanges: 'Make changes to your account',
    language: 'Language',
    appLanguage: 'App display language',
    theme: 'Theme',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    features: 'Features',
    faq: 'FAQ',
    heroBadge: 'Built for Khmer shop owners',
    heroTitleLineOne: 'Speak your sales.',
    heroTitleLineTwo: 'See your revenue.',
    heroMicroCopy: 'No mock bookkeeping. Every confirmed sale is saved through your account.',
    startFree: 'Start Free',
    averageLogTime: 'Average log time',
    voiceAccuracy: 'Voice extraction ready',
    syncedLedger: 'Synced ledger',
    cloudBackup: 'Cloud backup',
    designedForSpeed: 'Designed for daily shop speed',
    powerfulCapabilities: 'Powerful capabilities',
    voiceEngine: 'Khmer and English voice capture',
    voiceEngineCopy: 'Record a sale, answer follow-up questions when needed, and review the extracted items before saving.',
    analyticsTitle: 'Revenue that comes from saved sales',
    analyticsPaneCopy: 'Today, week, month, and history views read from your backend data with KHR and USD kept separate.',
    cloudTitle: 'Secure account workspace',
    cloudPaneCopy: 'Protected routes, stored tokens, and authenticated API calls keep your records tied to your login.',
    faqTitle: 'Common questions',
    faqOneQ: 'Can I review a sale before saving?',
    faqOneA: 'Yes. Voice results open in the existing review screen so you can edit items before confirming.',
    faqTwoQ: 'Does revenue come from real transactions?',
    faqTwoA: 'Yes. Dashboard and history totals are loaded from backend transaction data.',
    faqThreeQ: 'Can I use Khmer?',
    faqThreeA: 'Yes. The app UI supports English and Khmer, and Khmer mode uses Noto Sans Khmer.',
    changePassword: 'Change password',
    choosePassword: 'Choose a strong password',
    logout: 'Log out',
    logoutHint: 'Further secure your account for safety',
    createNewPassword: 'Create a New Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    passwordsNoMatch: 'Passwords do not match.',
    passwordChanged: 'Password changed successfully.',
    unablePassword: 'Unable to change password.',
    changing: 'Changing...',
    saleRecording: 'Sale Recording',
    assistantTitle: "Hi I'm Your Assistant",
    assistantSubtitle: 'for Daily Updates',
    paused: 'Paused',
    captured: 'Speech Captured',
    transcribing: 'Transcribing...',
    recording: 'Recording...',
    listeningSale: 'Listening for your sale details',
    tapMic: 'Tap the Micro to speak...',
    liveTranscription: 'Live transcription',
    readyToSend: 'Recording ready to send.',
    recordingAudio: 'Recording audio...',
    micRequired: 'Microphone access is required to record a sale.',
    recordBeforeSend: 'Record a sale before sending.',
    noSaleExtracted: 'No sale data was extracted. Please record again.',
    unableTranscribe: 'Unable to transcribe this recording.',
    answerQuestion: 'Answer clarification',
    sendAnswer: 'Send Answer',
    sendingAnswer: 'Sending...',
    followupPlaceholder: 'Type the missing sale detail',
    manualReviewNeeded: 'Some information is still missing. Please review and edit the sale before saving.',
    welcomeBackTitle: 'Welcome Back',
    signInSubtitle: 'Sign in to access your voice sales dashboard.',
    newHere: 'New here?',
    createAnAccount: 'Create an account',
    enterCredentials: 'Enter your credentials to continue.',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    signingIn: 'Signing In...',
    alreadyAccount: 'Already have an account?',
    enterDetails: 'Enter your details to create your workspace.',
    registering: 'Registering...',
    verifyEmail: 'Verify Email',
    verifySubtitle: 'Enter the code sent to your inbox.',
    alreadyVerified: 'Already verified?',
    confirmEmail: 'Confirm your email address to activate your workspace.',
    email: 'Email',
    verificationCode: 'Verification Code',
    verifying: 'Verifying...',
    accountSecurity: 'Account Security',
    resetRequestSubtitle: 'Request a reset link and regain access to your workspace.',
    rememberedPassword: 'Remembered your password?',
    backToSignIn: 'Back to Sign In',
    forgotPasswordTitle: 'Forgot Password',
    enterEmailReset: 'Enter your email to receive a password reset link.',
    sendingRequest: 'Sending Request...',
    sendReset: 'Send Verification Code',
    resetPassword: 'Reset Password',
    resetSubtitle: 'Choose a strong password to keep your account secure.',
    setNewPassword: 'Set New Password',
    enterNewPassword: 'Enter your new security credentials below.',
    confirmNewPassword: 'Confirm New Password',
    updatingPassword: 'Updating Password...',
    resetMissing: 'Reset token is missing from the link.',
    resetSuccess: 'Password reset successful! Redirecting to login...',
    resetLinkSent: 'A reset link has been sent to your email. Please check your inbox.',
    resetLinkFailed: 'Failed to send verification code. Please try again.',
    voiceBookkeeping: 'Voice bookkeeping for daily sales',
    landingCopy: 'Speak shop transactions naturally and turn them into structured sales records, revenue summaries, and reviewable ledgers.',
    revenueSummaries: 'Revenue summaries',
    revenueSummaryCopy: 'Review today, week, and month totals from one consistent dashboard.',
    confirmBeforeSaving: 'Confirm before saving',
    confirmBeforeSavingCopy: 'Edit extracted items before they become official sales records.',
    cloudConnected: 'Cloud connected',
    cloudConnectedCopy: 'Use the same account across browser devices once authenticated.',
    protectedWorkspace: 'Protected workspace',
    protectedWorkspaceCopy: 'Auth, bearer tokens, and route protection remain part of the app flow.',
    productCapabilities: 'Product capabilities',
    termsOfService: 'Terms of Service',
    lastUpdated: 'Last Updated: August 2026',
    termsAgree: 'By continuing, you agree to our',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
  },
  km: {
    home: 'ទំព័រដើម',
    history: 'ប្រវត្តិ',
    transactions: 'ប្រតិបត្តិការ',
    profile: 'ប្រវត្តិរូប',
    terms: 'លក្ខខណ្ឌ',
    privacy: 'ឯកជនភាព',
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    signIn: 'ចូលគណនី',
    signUp: 'ចុះឈ្មោះ',
    register: 'ចុះឈ្មោះ',
    createAccount: 'បង្កើតគណនី',
    openDashboard: 'បើកផ្ទាំងគ្រប់គ្រង',
    recordSale: 'ថតការលក់',
    welcomeBack: 'សូមស្វាគមន៍ {name}!',
    businessOverviewToday: 'នេះជាសង្ខេបអាជីវកម្មថ្ងៃនេះ។',
    todaysRevenue: 'ចំណូលថ្ងៃនេះ',
    filteredRevenue: 'ចំណូលតាមតម្រង',
    usdTotal: 'សរុប USD:',
    khrSeparate: 'សរុប KHR រក្សាទុកដាច់ដោយឡែក',
    totalOrders: 'ចំនួនការលក់',
    recentTransactions: 'ប្រតិបត្តិការថ្មីៗ',
    viewAll: 'មើលទាំងអស់',
    noTransactions: 'មិនទាន់មានប្រតិបត្តិការ។',
    loadingTransactions: 'កំពុងផ្ទុកប្រតិបត្តិការ...',
    unableDashboard: 'មិនអាចផ្ទុកទិន្នន័យផ្ទាំងគ្រប់គ្រងបាន។',
    unableHistory: 'មិនអាចផ្ទុកទិន្នន័យប្រវត្តិបាន។',
    productSummary: 'សង្ខេបផលិតផល',
    totalItems: 'ប្រភេទសរុប',
    productTypes: 'ប្រភេទផលិតផល',
    totalQuantity: 'បរិមាណសរុប',
    items: 'មុខទំនិញ',
    product: 'ផលិតផល',
    qty: 'ចំនួន',
    unitPrice: 'តម្លៃឯកតា',
    total: 'សរុប',
    noProducts: 'មិនមានផលិតផលក្នុងរយៈពេលនេះ។',
    today: 'ថ្ងៃនេះ',
    thisWeek: 'សប្តាហ៍នេះ',
    thisMonth: 'ខែនេះ',
    selectDate: 'ជ្រើសរើសកាលបរិច្ឆេទ',
    reviewConfirmSale: 'ពិនិត្យ និងបញ្ជាក់ការលក់',
    editTransaction: 'កែប្រតិបត្តិការ',
    transactionDetails: 'ព័ត៌មានលម្អិតប្រតិបត្តិការ',
    aiExtractionComplete: 'ការដកស្រង់ដោយ AI រួចរាល់!',
    reviewBeforeSaving: 'យើងបានចាប់យកព័ត៌មាន។ សូមពិនិត្យចំនួន និងតម្លៃមុនរក្សាទុក។',
    rerecord: 'ថតឡើងវិញ',
    foundItems: 'យើងរកឃើញមុខទំនិញខាងក្រោម៖',
    totalAmount: 'ចំនួនទឹកប្រាក់សរុប៖',
    editItems: 'កែទំនិញ',
    confirmSaveSale: 'បញ្ជាក់ និងរក្សាទុក',
    saving: 'កំពុងរក្សាទុក...',
    noReviewItems: 'មិនមានមុខទំនិញសម្រាប់រក្សាទុក។',
    addOneItem: 'សូមមានមុខទំនិញយ៉ាងហោចណាស់មួយ មុនរក្សាទុក។',
    unableRequest: 'មិនអាចបំពេញសំណើបាន។ សូមព្យាយាមម្តងទៀត។',
    date: 'កាលបរិច្ឆេទ៖',
    totalKHR: 'សរុប KHR៖',
    totalUSD: 'សរុប USD៖',
    edit: 'កែ',
    delete: 'លុប',
    transactionSaved: 'រក្សាទុកប្រតិបត្តិការរួចរាល់',
    saleAdded: 'ការលក់ត្រូវបានបន្ថែមទៅចំណូលថ្ងៃនេះ។',
    recordAnotherSale: 'ថតការលក់មួយទៀត',
    backHome: 'ត្រឡប់ទៅទំព័រដើម',
    ownerName: 'ឈ្មោះម្ចាស់',
    firstName: 'នាមខ្លួន',
    lastName: 'នាមត្រកូល',
    businessName: 'ឈ្មោះអាជីវកម្ម',
    phoneNumber: 'លេខទូរស័ព្ទ',
    emailAddress: 'អ៊ីមែល',
    address: 'អាសយដ្ឋាន',
    cancel: 'បោះបង់',
    saveChanges: 'រក្សាទុកការកែប្រែ',
    profileUpdated: 'បានកែប្រវត្តិរូបរួចរាល់។',
    unableProfile: 'មិនអាចកែប្រវត្តិរូបបាន។',
    account: 'គណនី',
    myAccount: 'គណនីខ្ញុំ',
    makeChanges: 'កែប្រែព័ត៌មានគណនី',
    language: 'ភាសា',
    appLanguage: 'ភាសាបង្ហាញក្នុងកម្មវិធី',
    theme: 'រូបរាង',
    lightMode: 'រូបរាងភ្លឺ',
    darkMode: 'រូបរាងងងឹត',
    features: 'មុខងារ',
    faq: 'សំណួរ',
    heroBadge: 'បង្កើតសម្រាប់ម្ចាស់ហាងខ្មែរ',
    heroTitleLineOne: 'និយាយការលក់របស់អ្នក។',
    heroTitleLineTwo: 'មើលចំណូលរបស់អ្នក។',
    heroMicroCopy: 'គ្មានទិន្នន័យក្លែងក្លាយ។ ការលក់ដែលបានបញ្ជាក់ត្រូវបានរក្សាទុកតាមគណនីរបស់អ្នក។',
    startFree: 'ចាប់ផ្ដើមឥតគិតថ្លៃ',
    averageLogTime: 'ពេលកត់ត្រាជាមធ្យម',
    voiceAccuracy: 'ត្រៀមដកស្រង់សំឡេង',
    syncedLedger: 'បញ្ជីបានធ្វើសមកាលកម្ម',
    cloudBackup: 'រក្សាទុកលើ Cloud',
    designedForSpeed: 'រចនាសម្រាប់ល្បឿនប្រចាំថ្ងៃរបស់ហាង',
    powerfulCapabilities: 'សមត្ថភាពសំខាន់ៗ',
    voiceEngine: 'កត់ត្រាសំឡេងខ្មែរ និងអង់គ្លេស',
    voiceEngineCopy: 'ថតការលក់ ឆ្លើយសំណួរបន្ថែមបើចាំបាច់ ហើយពិនិត្យទំនិញដែលបានដកស្រង់មុនរក្សាទុក។',
    analyticsTitle: 'ចំណូលពីការលក់ដែលបានរក្សាទុក',
    analyticsPaneCopy: 'ទំព័រថ្ងៃនេះ សប្ដាហ៍ ខែ និងប្រវត្តិ អានពីទិន្នន័យប្រតិបត្តិការពិត ហើយរក្សា KHR និង USD ដាច់ដោយឡែក។',
    cloudTitle: 'កន្លែងការងារគណនីមានសុវត្ថិភាព',
    cloudPaneCopy: 'ផ្លូវដែលបានការពារ token ដែលបានរក្សាទុក និង API ដែលមានការផ្ទៀងផ្ទាត់ រក្សាកំណត់ត្រារបស់អ្នកឱ្យភ្ជាប់នឹងការចូលគណនី។',
    faqTitle: 'សំណួរដែលសួរញឹកញាប់',
    faqOneQ: 'តើខ្ញុំអាចពិនិត្យការលក់មុនរក្សាទុកបានទេ?',
    faqOneA: 'បាន។ លទ្ធផលសំឡេងនឹងបើកក្នុងទំព័រពិនិត្យដដែល ដើម្បីឱ្យអ្នកកែទំនិញមុនបញ្ជាក់។',
    faqTwoQ: 'តើចំណូលមកពីប្រតិបត្តិការពិតទេ?',
    faqTwoA: 'បាទ/ចាស។ ចំណូលក្នុងផ្ទាំងគ្រប់គ្រង និងប្រវត្តិ ត្រូវបានផ្ទុកពីទិន្នន័យប្រតិបត្តិការនៅ backend។',
    faqThreeQ: 'តើខ្ញុំអាចប្រើភាសាខ្មែរបានទេ?',
    faqThreeA: 'បាន។ UI គាំទ្រអង់គ្លេស និងខ្មែរ ហើយរូបរាងខ្មែរប្រើ Noto Sans Khmer។',
    changePassword: 'ប្តូរពាក្យសម្ងាត់',
    choosePassword: 'ជ្រើសពាក្យសម្ងាត់រឹងមាំ',
    logout: 'ចេញពីគណនី',
    logoutHint: 'ការពារគណនីរបស់អ្នកបន្ថែម',
    createNewPassword: 'បង្កើតពាក្យសម្ងាត់ថ្មី',
    currentPassword: 'ពាក្យសម្ងាត់បច្ចុប្បន្ន',
    newPassword: 'ពាក្យសម្ងាត់ថ្មី',
    confirmPassword: 'បញ្ជាក់ពាក្យសម្ងាត់',
    passwordsNoMatch: 'ពាក្យសម្ងាត់មិនដូចគ្នា។',
    passwordChanged: 'បានប្តូរពាក្យសម្ងាត់រួចរាល់។',
    unablePassword: 'មិនអាចប្តូរពាក្យសម្ងាត់បាន។',
    changing: 'កំពុងប្តូរ...',
    saleRecording: 'ថតការលក់',
    assistantTitle: 'សួស្តី ខ្ញុំជាជំនួយការរបស់អ្នក',
    assistantSubtitle: 'សម្រាប់បច្ចុប្បន្នភាពប្រចាំថ្ងៃ',
    paused: 'បានផ្អាក',
    captured: 'ថតរួចរាល់',
    transcribing: 'កំពុងបម្លែងសំឡេង...',
    recording: 'កំពុងថត...',
    listeningSale: 'កំពុងស្តាប់ព័ត៌មានការលក់',
    tapMic: 'ចុចមីក្រូហ្វូនដើម្បីនិយាយ...',
    liveTranscription: 'អត្ថបទបម្លែងផ្ទាល់',
    readyToSend: 'សំឡេងរួចរាល់សម្រាប់ផ្ញើ។',
    recordingAudio: 'កំពុងថតសំឡេង...',
    micRequired: 'ត្រូវការអនុញ្ញាតមីក្រូហ្វូនដើម្បីថតការលក់។',
    recordBeforeSend: 'សូមថតការលក់មុនផ្ញើ។',
    noSaleExtracted: 'មិនអាចដកស្រង់ទិន្នន័យការលក់បាន។ សូមថតឡើងវិញ។',
    unableTranscribe: 'មិនអាចបម្លែងសំឡេងនេះបាន។',
    answerQuestion: 'ឆ្លើយសំណួរបន្ថែម',
    sendAnswer: 'ផ្ញើចម្លើយ',
    sendingAnswer: 'កំពុងផ្ញើ...',
    followupPlaceholder: 'បញ្ចូលព័ត៌មានការលក់ដែលខ្វះ',
    manualReviewNeeded: 'ព័ត៌មានខ្លះនៅខ្វះ។ សូមពិនិត្យ និងកែមុនរក្សាទុក។',
    welcomeBackTitle: 'សូមស្វាគមន៍ត្រឡប់មកវិញ',
    signInSubtitle: 'ចូលគណនីដើម្បីប្រើផ្ទាំងលក់ដោយសំឡេង។',
    newHere: 'អ្នកថ្មីមែនទេ?',
    createAnAccount: 'បង្កើតគណនី',
    enterCredentials: 'បញ្ចូលព័ត៌មានដើម្បីបន្ត។',
    password: 'ពាក្យសម្ងាត់',
    forgotPassword: 'ភ្លេចពាក្យសម្ងាត់?',
    signingIn: 'កំពុងចូល...',
    alreadyAccount: 'មានគណនីរួចហើយ?',
    enterDetails: 'បញ្ចូលព័ត៌មានដើម្បីបង្កើតកន្លែងធ្វើការ។',
    registering: 'កំពុងចុះឈ្មោះ...',
    verifyEmail: 'ផ្ទៀងផ្ទាត់អ៊ីមែល',
    verifySubtitle: 'បញ្ចូលលេខកូដដែលបានផ្ញើទៅអ៊ីមែល។',
    alreadyVerified: 'បានផ្ទៀងផ្ទាត់រួចហើយ?',
    confirmEmail: 'បញ្ជាក់អ៊ីមែលរបស់អ្នកដើម្បីបើកគណនី។',
    email: 'អ៊ីមែល',
    verificationCode: 'លេខកូដផ្ទៀងផ្ទាត់',
    verifying: 'កំពុងផ្ទៀងផ្ទាត់...',
    accountSecurity: 'សុវត្ថិភាពគណនី',
    resetRequestSubtitle: 'ស្នើតំណកំណត់ឡើងវិញដើម្បីចូលប្រើគណនី។',
    rememberedPassword: 'នឹកឃើញពាក្យសម្ងាត់វិញ?',
    backToSignIn: 'ត្រឡប់ទៅចូលគណនី',
    forgotPasswordTitle: 'ភ្លេចពាក្យសម្ងាត់',
    enterEmailReset: 'បញ្ចូលអ៊ីមែលដើម្បីទទួលតំណកំណត់ឡើងវិញ។',
    sendingRequest: 'កំពុងផ្ញើសំណើ...',
    sendReset: 'ផ្ញើលេខកូដផ្ទៀងផ្ទាត់',
    resetPassword: 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
    resetSubtitle: 'ជ្រើសពាក្យសម្ងាត់រឹងមាំដើម្បីការពារគណនី។',
    setNewPassword: 'កំណត់ពាក្យសម្ងាត់ថ្មី',
    enterNewPassword: 'បញ្ចូលព័ត៌មានសុវត្ថិភាពថ្មីខាងក្រោម។',
    confirmNewPassword: 'បញ្ជាក់ពាក្យសម្ងាត់ថ្មី',
    updatingPassword: 'កំពុងកែពាក្យសម្ងាត់...',
    resetMissing: 'បាត់តំណកូដកំណត់ឡើងវិញ។',
    resetSuccess: 'បានកំណត់ពាក្យសម្ងាត់ឡើងវិញ។ កំពុងប្តូរទៅចូលគណនី...',
    resetLinkSent: 'តំណកំណត់ឡើងវិញត្រូវបានផ្ញើទៅអ៊ីមែលរបស់អ្នក។ សូមពិនិត្យប្រអប់សំបុត្រ។',
    resetLinkFailed: 'មិនអាចផ្ញើលេខកូដផ្ទៀងផ្ទាត់បាន។ សូមព្យាយាមម្តងទៀត។',
    voiceBookkeeping: 'កត់ត្រាការលក់ប្រចាំថ្ងៃដោយសំឡេង',
    landingCopy: 'និយាយការលក់ក្នុងហាង ហើយបម្លែងទៅជាកំណត់ត្រាលក់ សង្ខេបចំណូល និងបញ្ជីដែលអាចពិនិត្យបាន។',
    revenueSummaries: 'សង្ខេបចំណូល',
    revenueSummaryCopy: 'ពិនិត្យសរុបថ្ងៃនេះ សប្តាហ៍នេះ និងខែនេះពីផ្ទាំងតែមួយ។',
    confirmBeforeSaving: 'បញ្ជាក់មុនរក្សាទុក',
    confirmBeforeSavingCopy: 'កែទំនិញដែលបានដកស្រង់ មុនវាក្លាយជាកំណត់ត្រាផ្លូវការ។',
    cloudConnected: 'ភ្ជាប់តាមគណនី',
    cloudConnectedCopy: 'ប្រើគណនីដូចគ្នាលើឧបករណ៍ផ្សេងៗបន្ទាប់ពីចូលគណនី។',
    protectedWorkspace: 'កន្លែងការងារមានការពារ',
    protectedWorkspaceCopy: 'រក្សា Auth, Bearer token និងការពារផ្លូវក្នុងលំហូរកម្មវិធី។',
    productCapabilities: 'សមត្ថភាពផលិតផល',
    termsOfService: 'លក្ខខណ្ឌសេវាកម្ម',
    lastUpdated: 'កែប្រែចុងក្រោយ៖ សីហា ២០២៦',
    termsAgree: 'ដោយបន្ត អ្នកយល់ព្រមនឹង',
    and: 'និង',
    privacyPolicy: 'គោលការណ៍ឯកជនភាព',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem(STORAGE_KEY) || 'en');

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage: setLanguageState,
    toggleLanguage: () => setLanguageState((current) => (current === 'en' ? 'km' : 'en')),
    t: (key, values = {}) => {
      const template = translations[language]?.[key] || translations.en[key] || key;
      return Object.entries(values).reduce(
        (text, [name, value]) => text.replace(`{${name}}`, value),
        template
      );
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
