"""add telegram fields to users

Revision ID: 9fa969513bd6
Revises: 20260901_0001
Create Date: 2026-09-06 13:07:38.369581
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9fa969513bd6'
down_revision: Union[str, Sequence[str], None] = '20260901_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chk_sale_items_amount_nonneg'), 'sale_items', type_='check')
    op.drop_constraint(op.f('chk_sale_items_currency'), 'sale_items', type_='check')
    op.drop_constraint(op.f('chk_sale_items_quantity_positive'), 'sale_items', type_='check')
    op.drop_constraint(op.f('chk_sale_items_unit_price_nonneg'), 'sale_items', type_='check')
    op.drop_constraint(op.f('chk_sales_total_khr_nonneg'), 'sales', type_='check')
    op.drop_constraint(op.f('chk_sales_total_usd_nonneg'), 'sales', type_='check')
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_id')
    op.create_check_constraint(op.f('chk_sales_total_usd_nonneg'), 'sales', '(`total_usd` >= 0)')
    op.create_check_constraint(op.f('chk_sales_total_khr_nonneg'), 'sales', '(`total_khr` >= 0)')
    op.create_check_constraint(op.f('chk_sale_items_unit_price_nonneg'), 'sale_items', '(`unit_price` >= 0)')
    op.create_check_constraint(op.f('chk_sale_items_quantity_positive'), 'sale_items', '(`quantity` > 0)')
    op.create_check_constraint(op.f('chk_sale_items_currency'), 'sale_items', "(`currency` in (_utf8mb4'KHR',_utf8mb4'USD'))")
    op.create_check_constraint(op.f('chk_sale_items_amount_nonneg'), 'sale_items', '(`amount` >= 0)')
    # ### end Alembic commands ###
